---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/legal
  label: Legal
  create: all
  match: "**/*"
- type: directory
  path: content/spaces
  label: Spaces
  create: all
  match: "**/*"
  templates:
  - spacesinformations
- type: document
  path: site.config.json
  label: Configuration
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
